name: Upload S3
description: 'Upload directory to S3'
author: 'Dong Keon Kim'
branding:
  icon: 'upload-cloud'
  color: 'orange'
inputs:
  aws_key_id:
    description: 'aws key id'
    required: true
  aws_secret_access_key:
    description: 'aws secret access key'
    required: true
  aws_bucket:
    description: 'aws bucket name'
    required: true
  source_dir:
    required: true
    description: 'directory to upload'
  destination_dir:
    required: false
    default: /
    description: 'destination directory for upload'
  endpoint:
    required: false
    description: 'endpoint URI to send requests'
  mode:
    required: false
    description: 'upload/download'
  source_ignore:
    required: false
    description: 'ignore'
outputs:
  object_key:
    description: 'object key'
  object_result:
    description: 'upload object_result'
runs:
  using: 'node20'
  main: 'dist/index.js'
